# in order to use this template follow the comments and change the infos
name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # add this secrets to your repo
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/repo" # change to the name of your directory name in your machine

      - name: Run production scripts on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} # if you created your droplet with ssh auth use this line
          # password: ${{ secrets.SSH_PASSWORD }} # if you created your droplet with password auth use this line 
          # change "repo" to the name of your directory name in your machine
          script: |
            cd ~/repo 
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart repo
